services:
  caddy:
    image: caddy
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile

  server:
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
