services:
  caddy:
    image: caddy
    ports:
      - "80:80"
      - "443:443"
      # setting up of port forwarding here allows caddy to listen from the host (whether in production
      # or on localhost).
      # Within the caddyfile, there are settings set up to reverse proxy traffic from this port to server:3000
    restart: always
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
      # set up port forwarding here - so that we can actually connect using psql on the host machine
  server:
    depends_on: [db]
    build:
      context: ./
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
      # set up port forwarding here in case we need to connect from the actual host machine
