// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package postgressqlqueries

import (
	"database/sql"
)

type User struct {
	ID             int64
	Email          string
	HashedPassword string
	CreatedOn      sql.NullTime
	UpdatedOn      sql.NullTime
	IsActive       bool
}
